spring:
  application:
    name: api-documento
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/keycloak-feign
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: backend
            client-secret: pO1TaXXJJnsws4dmoMnLoIO2Myb6Mqxi
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/keycloak-feign/protocol/openid-connect/token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8084
